package sysc4806.project.models;

public enum Program {
    MECHANICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    SOFTWARE_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    COMPUTER_ENGINEERING,
    CHEMICAL_ENGINEERING
}
